---

- name: Network Getting Started First Playbook
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    fruit: "apple"
  tasks:

    - name: "print extra vars"
      debug:
        msg: "The fruit is {{ fruit }}"
